#include <stdio.h>
#include <stdlib.h>
#include <unistd.h> // sleep Fonction
#include <time.h>

#include "matrice.h"
#include "game_control.h"
#include "auto_resolve.h"

#define TRUE 1
#define FALSE 0

void bienvenue();
void main_menu();
void player_joue_menu();
int masque_menu();
void auto_joue_menu();
void auto_genere_menu();

int main() {
    // initialisation de la seed sur le temps
    srand(time(NULL));

    // bienvenue message
    bienvenue();

    printf("\n");

    // Select menu
    main_menu();

    printf("\n\n-+-+-+-+-+-+-+-+-+\nSortie du programme.\n-+-+-+-+-+-+-+-+-+\n");

    return 0;
}

void bienvenue()
/*
 * Fonction: bienvenue
 * -----------------
 * Just a bienvenue block
 * Sign generated by : https://fsymbols.com/generators/wide/
 */
{
    printf("\033[0;34m░░░░░░░░░░░░░░░░░░\033[0m░░░░░░░░░░░░░░░░░░░\033[0;31m░░░░░░░░░░░░░░░░░░░\n"
           "\033[0;34m████████╗ ░█████╗░\033[0m ██╗░░██╗ ██╗░░░██╗\033[0;31m ███████╗ ██╗░░░██╗\n"
           "\033[0;34m╚══██╔══╝ ██╔══██╗\033[0m ██║░██╔╝ ██║░░░██║\033[0;31m ╚════██║ ██║░░░██║\n"
           "\033[0;34m░░░██║░░░ ███████║\033[0m █████═╝░ ██║░░░██║\033[0;31m ░░███╔═╝ ██║░░░██║\n"
           "\033[0;34m░░░██║░░░ ██╔══██║\033[0m ██╔═██╗░ ██║░░░██║\033[0;31m ██╔══╝░░ ██║░░░██║\n"
           "\033[0;34m░░░██║░░░ ██║░░██║\033[0m ██║░╚██╗ ╚██████╔╝\033[0;31m ███████╗ ╚██████╔╝\n"
           "\033[0;34m░░░╚═╝░░░ ╚═╝░░╚═╝\033[0m ╚═╝░░╚═╝ ░╚═════╝░\033[0;31m ╚══════╝ ░╚═════╝░\n"
           "\033[0;34m░░░░░░░░░░░░░░░░░░\033[0m░░░░░░░Marque dépos\033[0;31mée le 31/01/2006░░░\n");
    printf("\033[0m");
}
void main_menu()
/*
 * Fonction: main_menu
 * -----------------
 * Menu principal, l'utilisateur à trois choix possible
 */
{
    int choix = -1;
    do {
        printf("\033[1mMenu principal. \033[2;34mChoisissez votre menu : \033[0m\n"
               "1 - Résoudre une grille.\n"
               "2 - Résoudre automatiquement une grille de Takuzu.\n"
               "3 - Génère une grille de Takuzu.\n"
               "4 - Quitter le programme.\n"
               "\033[0;34mChoix : \033[0m");
        scanf("%d", &choix);
        switch (choix) {
            case 1:
            {
                player_joue_menu();
                break;
            }
            case 2:
            {
                auto_joue_menu();
                break;
            }
            case 3:
            {
                auto_genere_menu();
                break;
            }
            case 4:
            {
                break;
            }
            default: printf("Choix non valide. SVP réessayez à nouveau.\n");
        }
    } while (choix != 4);
}

void player_joue_menu()
/*
 * Fonction: player_joue_menu
 * -----------------
 * Menu de la partie I : Laisser un joueur résoudre une grille.
 * L'utilisateur à 4 choix possible :
 * Grille 4*4, Grile 8*8, Grille 16*16, Revenir au menu principal
 * Après avoir choisi, il choisit son masque via la fonction masque_menu()
 * Le jeu se lance par la fonction game (game_control.c)
 */
{
    int choix = -1;
    do {
        printf("\033[0;34mQuelle taille de grille souhaitez-vous ?\n\033[0mTailles disponible : \033[0;32m4\033[0m, \033[0;33m8, \033[0;31m16 \033[0m(Choisissez \033[0;36m0\033[0m pour revenir au menu principal)\n\033[0;34mChoix :\033[0m ");
        scanf("%d", &choix);

        if (choix == 4 || choix == 8 || choix == 16)
        {
            int** grille_solution = creation_mat_modele(choix);
            int** grille_jeu = creation_mat_modele(choix);

            int choix_masque = masque_menu();

            printf("\n-+-+-+-+-+-+-+-+-+ MASQUE -+-+-+-+-+-+-+-+-+\n");
            int** grille_masque = takuzu_utilisateur(grille_solution, grille_jeu, choix, choix_masque);
            affichage_matrice(grille_masque, choix, 2);
            printf("\n-+-+-+-+-+-+-+-^^ MASQUE ^^-+-+-+-+-+-+-+-+-\n");


            game(grille_jeu, grille_solution, choix);
            sleep(3); // Cooldown : 3 sec le temps qu'il regarde sa grille
            printf("Retour au ");
            libere_matrice(choix, grille_jeu);
            libere_matrice(choix, grille_solution);
        }

    } while (!(choix == 4 || choix == 8 || choix == 16 || choix == 0));
    //printf("\n-+-+-+-+-+-+-+-+-+\nSortie du grid_menu().\n-+-+-+-+-+-+-+-+-+\n");
}

void auto_joue_menu()
/*
 * Fonction: auto_joue_menu
 * -----------------
 * Menu de la partie II : Joue automatique
 * L'utilisateur à 4 choix possible :
 * Grille 4*4, Grile 8*8, Grille 16*16, Revenir au menu principal
 * Après avoir choisi, il choisit son masque via la fonction masque_menu()
 * Le jeu se lance par la fonction game (game_control.c)
 */
{
    int choix = -1;
    do {
        printf("\033[0;34mQuelle taille de grille souhaitez-vous ?\n\033[0mTailles disponible : \033[0;32m4\033[0m, \033[0;33m8, \033[0;31m16 \033[0m(Choisissez \033[0;36m0\033[0m pour revenir au menu principal)\n\033[0;34mChoix :\033[0m ");
        scanf("%d", &choix);

        if (choix == 4 || choix == 8 || choix == 16)
        {
            int** grille_solution = creation_mat_modele(choix);
            int** grille_jeu = creation_mat_modele(choix);

            int choix_masque = masque_menu();

            printf("\n-+-+-+-+-+-+-+-+-+ MASQUE -+-+-+-+-+-+-+-+-+\n");
            int** grille_masque = takuzu_utilisateur(grille_solution, grille_jeu, choix, choix_masque);
            affichage_matrice(grille_masque, choix, 2);
            printf("\n-+-+-+-+-+-+-+-^^ MASQUE ^^-+-+-+-+-+-+-+-+-\n");

            auto_resolve(grille_jeu, grille_solution, choix);

            printf("Retour au ");
            libere_matrice(choix, grille_jeu);
            libere_matrice(choix, grille_solution);
        }
    } while (!(choix == 4 || choix == 8 || choix == 16 || choix == 0));
}

void auto_genere_menu()
/*
 * Fonction: auto_genere_menu
 * -----------------
 * Menu de la partie III : Génération automatique de grille
 * L'utilisateur à 4 choix possible :
 * Grille 4*4, Grile 8*8, Grille 16*16, Revenir au menu principal
 * On lui présente ensuite la grille
 */
{
    int choix = -1;
    do {
        printf("\033[0;34mQuelle taille de grille souhaitez-vous ?\n\033[0mTailles disponible : \033[0;32m4\033[0m, \033[0;33m8, \033[0;31m16 \033[0m(Choisissez \033[0;36m0\033[0m pour revenir au menu principal)\n\033[0;34mChoix :\033[0m ");
        scanf("%d", &choix);

        if (choix == 4 || choix == 8)
        {
            int** grille_solution = generation_solution(choix, NULL);
            //int** grille_jeu = generation_solution(choix);

            affichage_matrice(grille_solution, choix, 1);

            /*
            int choix_masque = masque_menu();

            printf("\n-+-+-+-+-+-+-+-+-+ MASQUE -+-+-+-+-+-+-+-+-+\n");
            int** grille_masque = takuzu_utilisateur(grille_solution, grille_jeu, choix, choix_masque);
            affichage_matrice(grille_masque, choix, 2);
            printf("\n-+-+-+-+-+-+-+-^^ MASQUE ^^-+-+-+-+-+-+-+-+-\n");
            */


            printf("Retour au ");
            //libere_matrice(choix, grille_jeu);
            libere_matrice(choix, grille_solution);
        }
        /*
        else {
            if (choix == 16) {
                printf("\n\033[0;31m*Zone pas encore terminée*\n");
            } else {
                if (choix == 0) {
                    printf("Sortie en cours...\n");
                } else {
                    printf("Taille indisponible ou non reconnue. Veuillez réessayer.\n");
                }
            }
        }*/

    } while (!(choix == 4 || choix == 8 || choix == 0));
}

int masque_menu()
/*
 * Fonction: masque_menu
 * -----------------
 * Menu de choix de masque
 * L'utilisateur à 2 choix possible :
 * Masque automatique
 * Masque manuel
 */
{
    int choix_masque = -1;

    do
    {
        printf("\033[0;34mVeuillez choisir un type de masque.\033[0m\n"
               "1. Masque manuellement saisie.\n"
               "2. Masque aléatoire.\n"
               "\033[0;34mChoix :\033[0m ");
        scanf("%d", &choix_masque);

        if (!(choix_masque == 1 || choix_masque == 2))
        {
            printf("Choix du masque incorrect. Veuillez réessayer.\n");
        }

    } while (!(choix_masque == 1 || choix_masque == 2));

    return choix_masque;
}